/*
 * Copyright (c) 2020 LG Electronics Inc.
 * SPDX-License-Identifier: MIT
 */

#ifndef INCLUDE_SENTINEL_DOCGENERATOR_EMPTYINDEXHTMLGENERATOR_HPP_
#define INCLUDE_SENTINEL_DOCGENERATOR_EMPTYINDEXHTMLGENERATOR_HPP_

#include <stddef.h>
#include <string>
#include <vector>
#include "sentinel/docGenerator/DocGenerator.hpp"

namespace sentinel {

/**
 * @brief EmptyIndexHtmlGenerator class
 */
class EmptyIndexHtmlGenerator : public DocGenerator {
 public:
  /**
   * @brief make empty index html string
   */
  inline std::string str() const override {
    return emptyIndexHtmlContent;
  }

 private:
  std::string emptyIndexHtmlContent =
      R"html(<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Sentinel — Mutation Testing Report</title>
  <link rel="stylesheet" href="style.css"/>
</head>
<body>
<div class="wrap">
  <header class="hdr">
    <div class="hdr__left">
      <h1>Mutation Testing Report</h1>
    </div>
  </header>
  <div class="panel" style="text-align:center;padding:40px">
    <p style="color:var(--text-muted)">There is no mutated file in this project.</p>
  </div>
  <footer class="ftr">Report generated by <a href="https://github.com/shift-left-test/sentinel">Sentinel</a></footer>
</div>
</body>
</html>
)html";
};

}  // namespace sentinel

#endif  // INCLUDE_SENTINEL_DOCGENERATOR_EMPTYINDEXHTMLGENERATOR_HPP_
