 /*
  MIT License

  Copyright (c) 2020 Sangmo Kang

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

#ifndef INCLUDE_SENTINEL_DOCGENERATOR_EMPTYINDEXHTMLGENERATOR_HPP_
#define INCLUDE_SENTINEL_DOCGENERATOR_EMPTYINDEXHTMLGENERATOR_HPP_

#include <stddef.h>
#include <string>
#include <vector>
#include "sentinel/docGenerator/DOCGenerator.hpp"

namespace sentinel {

/**
 * @brief EmptyIndexHTMLGenerator class
 */
class EmptyIndexHTMLGenerator : public DOCGenerator {
 public:
  /**
   * @brief make empty index html string
   */
  inline std::string str() override {
    return emptyIndexHtmlContent;
  }

 private:
  std::string emptyIndexHtmlContent =
      R"a1b2(<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="style.css"/>
    </head>
    <body>
        <h1>Sentinel Mutation Coverage Report</h1>
        <h3>Proejct Summary</h3>
        <h5>There is no mutated file in this project.</h5>
        <hr/>
        <h5>Report generated by <a href="http://mod.lge.com/hub/yocto/sentinel">Sentinel</a>
        </h5>
    </body>
</html>
)a1b2";
};

}  // namespace sentinel

#endif  // INCLUDE_SENTINEL_DOCGENERATOR_EMPTYINDEXHTMLGENERATOR_HPP_
