 /*
  MIT License

  Copyright (c) 2020 Sung Gon Kim

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

#ifndef INCLUDE_SENTINEL_HTMLREPORT_HPP_
#define INCLUDE_SENTINEL_HTMLREPORT_HPP_

#include <tinyxml2/tinyxml2.h>
#include <map>
#include <string>
#include <tuple>
#include <vector>
#include "sentinel/Report.hpp"


namespace sentinel {

/**
 * @brief HTMLReport class
 */
class HTMLReport : public Report {
 public:
  /**
   * @brief Default constructor
   *
   * @param resultsPath directory path of mutation results
   * @param sourcePath directory path of source files
   */
  HTMLReport(const std::string& resultsPath, const std::string& sourcePath);

  /**
   * @brief save html format result to path
   *
   * @param dirPath
   * @throw InvalidArgumentException when path is not directory
   */
  void save(const std::string& dirPath) override;

 private:
  /**
   * @brief makeIndexHtml
   *
   * @param groupByDirPath
   * @param groupByPath
   * @param totNumberOfMutation
   * @param totNumberOfDetecedMutation
   * @param root index or not
   * @param currentDirPath current key of groupByDirPath (used in non root)
   * @param outputDir
   */
  void makeIndexHtml(
      std::map<std::string,
      std::tuple<std::vector<const MutationResult*>*, int, int, int>* >*
      pGroupByDirPath,
      std::map<std::string,
      std::tuple<std::vector<const MutationResult*>*, int, int>* >*
      pGroupByPath,
      int totNumberOfMutation, int totNumberOfDetectedMutation, bool root,
      const std::string& currentDirPath, const std::string& outputDir);

  /**
   * @brief makeSourceHtml
   *
   * @param MRs Mutation Resulsts of a source file
   * @param srcPath
   * @param outputDir
   */
  void makeSourceHtml(
      std::vector<const MutationResult*>* MRs, const std::string& srcPath,
      const std::string& outputDir);

  /**
   * @brief insert new node at the end of parent
   *
   * @param doc root document
   * @param parent node
   * @param elementName new element's name
   * @param elementText new element's text if exists
   */
  tinyxml2::XMLElement* insertNewNode(tinyxml2::XMLDocument* doc,
                                      tinyxml2::XMLNode* parent,
                                      const char* elementName,
                                      const char* elementText);

  std::string styleCssContent = ""
      "html, body, div, span, p, blockquote, pre {\n"
      "    margin: 0;\n"
      "    padding: 0;\n"
      "    border: 0;\n"
      "    outline: 0;\n"
      "    font-weight: inherit;\n"
      "    font-style: inherit;\n"
      "    font-size: 100%;\n"
      "    font-family: inherit;\n"
      "    vertical-align: baseline;\n"
      "}\n"
      "\n"
      "body{\n"
      "    line-height: 1;\n"
      "    color: black;\n"
      "    background: white;\n"
      "    margin-left: 20px;\n"
      "}\n"
      "\n"
      ".src { \n"
      "    border: 1px solid #dddddd;\n"
      "    padding-top: 10px;\n"
      "    padding-right: 5px;\n"
      "    padding-left: 5px;\n"
      "    font-family: Consolas, Courier, monospace;\n"
      "}\n"
      "\n"
      ".covered {\n"
      "    background-color: #ddffdd;\n"
      "}\n"
      "\n"
      ".uncovered {\n"
      "    background-color: #ffdddd;\n"
      "}\n"
      "\n"
      ".killed, .KILLED {\n"
      "    background-color: #aaffaa;\n"
      "}\n"
      "\n"
      ".survived, .SURVIVED {\n"
      "    background-color: #ffaaaa;\n"
      "}\n"
      "\n"
      ".uncertain {\n"
      "    background-color: #dde7ef;\n"
      "}\n"
      "\n"
      ".run_error {\n"
      "    background-color: #dde7ef;\n"
      "}\n"
      "\n"
      ".na {\n"
      "    background-color: #eeeeee;\n"
      "}\n"
      "\n"
      ".timed_out {\n"
      "    background-color: #dde7ef;\n"
      "}\n"
      "\n"
      ".non_viable {\n"
      "    background-color: #aaffaa;\n"
      "}\n"
      "\n"
      ".memory_error {\n"
      "    background-color: #dde7ef;\n"
      "}\n"
      "\n"
      ".not_started {\n"
      "    background-color: #dde7ef; color : red\n"
      "}\n"
      "\n"
      ".no_coverage {\n"
      "    background-color: #ffaaaa;\n"
      "}\n"
      "\n"
      ".tests {\n"
      "    width: 50%;\n"
      "    float: left;\n"
      "}\n"
      "\n"
      ".mutees {\n"
      "    float: right;\n"
      "    width: 50%;\n"
      "}\n"
      "\n"
      ".unit {\n"
      "    padding-top: 20px;\n"
      "    clear: both;\n"
      "}\n"
      "\n"
      ".coverage_bar {\n"
      "    display: inline-block;\n"
      "    height: 1.1em;\n"
      "    width: 130px;\n"
      "    background: #FAA;\n"
      "    margin: 0 5px;\n"
      "    vertical-align: middle;\n"
      "    border: 1px solid #AAA;\n"
      "    position: relative;\n"
      "}\n"
      "\n"
      ".coverage_complete {\n"
      "    display: inline-block;\n"
      "    height: 100%;\n"
      "    background: #DFD;\n"
      "    float: left;\n"
      "}\n"
      "\n"
      ".coverage_legend {\n"
      "    position: absolute;\n"
      "    height: 100%;\n"
      "    width: 100%;\n"
      "    left: 0;\n"
      "    top: 0;\n"
      "    text-align: center;\n"
      "}\n"
      "\n"
      ".line, .mut {\n"
      "    vertical-align: middle;\n"
      "}\n"
      "\n"
      ".coverage_percentage {\n"
      "    display: inline-block;\n"
      "    width: 3em;\n"
      "    text-align: right;\n"
      "}\n"
      "\n"
      ".pop {\n"
      "    outline:none;\n"
      "}\n"
      "\n"
      ".pop strong {\n"
      "    line-height: 30px;\n"
      "}\n"
      "\n"
      ".pop {\n"
      "    text-decoration: none;\n"
      "}\n"
      "\n"
      ".pop span {\n"
      "    z-index: 10;\n"
      "    display: none;\n"
      "    padding: 14px 20px;\n"
      "    margin-top: -30px;\n"
      "    margin-left: 28px;\n"
      "    width: 800px;\n"
      "    line-height: 16px;\n"
      "    word-wrap: break-word;\n"
      "    border-radius: 4px;\n"
      "    -moz-border-radius: 4px;\n"
      "    -webkit-border-radius: 4px;\n"
      "    -moz-box-shadow: 5px 5px 8px #CCC;\n"
      "    -webkit-box-shadow: 5px 5px 8px #CCC;\n"
      "    box-shadow: 5px 5px 8px #CCC;\n"
      "}\n"
      "\n"
      ".pop:hover span {\n"
      "    display: inline;\n"
      "    position: absolute;\n"
      "    color: #111;\n"
      "    border: 1px solid #DCA;\n"
      "    background: #fffAF0;\n"
      "}\n"
      "\n"
      ".width-1 {\n"
      "    width: 1%;\n"
      "}\n"
      "\n"
      ".width-2 {\n"
      "    width: 2%;\n"
      "}\n"
      "\n"
      ".width-3 {\n"
      "    width: 3%;\n"
      "}\n"
      "\n"
      ".width-4 {\n"
      "    width: 4%;\n"
      "}\n"
      "\n"
      ".width-5 {\n"
      "    width: 5%;\n"
      "}\n"
      "\n"
      ".width-6 {\n"
      "    width: 6%;\n"
      "}\n"
      "\n"
      ".width-7 {\n"
      "    width: 7%;\n"
      "}\n"
      "\n"
      ".width-8 {\n"
      "    width: 8%;\n"
      "}\n"
      "\n"
      ".width-9 {\n"
      "    width: 9%;\n"
      "}\n"
      "\n"
      ".width-10 {\n"
      "    width: 10%;\n"
      "}\n"
      "\n"
      ".width-11 {\n"
      "    width: 11%;\n"
      "}\n"
      "\n"
      ".width-12 {\n"
      "    width: 12%;\n"
      "}\n"
      "\n"
      ".width-13 {\n"
      "    width: 13%;\n"
      "}\n"
      "\n"
      ".width-14 {\n"
      "    width: 14%;\n"
      "}\n"
      "\n"
      ".width-15 {\n"
      "    width: 15%;\n"
      "}\n"
      "\n"
      ".width-16 {\n"
      "    width: 16%;\n"
      "}\n"
      "\n"
      ".width-17 {\n"
      "    width: 17%;\n"
      "}\n"
      "\n"
      ".width-18 {\n"
      "    width: 18%;\n"
      "}\n"
      "\n"
      ".width-19 {\n"
      "    width: 19%;\n"
      "}\n"
      "\n"
      ".width-20 {\n"
      "    width: 20%;\n"
      "}\n"
      "\n"
      ".width-21 {\n"
      "    width: 21%;\n"
      "}\n"
      "\n"
      ".width-22 {\n"
      "    width: 22%;\n"
      "}\n"
      "\n"
      ".width-23 {\n"
      "    width: 23%;\n"
      "}\n"
      "\n"
      ".width-24 {\n"
      "    width: 24%;\n"
      "}\n"
      "\n"
      ".width-25 {\n"
      "    width: 25%;\n"
      "}\n"
      "\n"
      ".width-26 {\n"
      "    width: 26%;\n"
      "}\n"
      "\n"
      ".width-27 {\n"
      "    width: 27%;\n"
      "}\n"
      "\n"
      ".width-28 {\n"
      "    width: 28%;\n"
      "}\n"
      "\n"
      ".width-29 {\n"
      "    width: 29%;\n"
      "}\n"
      "\n"
      ".width-30 {\n"
      "    width: 30%;\n"
      "}\n"
      "\n"
      ".width-31 {\n"
      "    width: 31%;\n"
      "}\n"
      "\n"
      ".width-32 {\n"
      "    width: 32%;\n"
      "}\n"
      "\n"
      ".width-33 {\n"
      "    width: 33%;\n"
      "}\n"
      "\n"
      ".width-34 {\n"
      "    width: 34%;\n"
      "}\n"
      "\n"
      ".width-35 {\n"
      "    width: 35%;\n"
      "}\n"
      "\n"
      ".width-36 {\n"
      "    width: 36%;\n"
      "}\n"
      "\n"
      ".width-37 {\n"
      "    width: 37%;\n"
      "}\n"
      "\n"
      ".width-38 {\n"
      "    width: 38%;\n"
      "}\n"
      "\n"
      ".width-39 {\n"
      "    width: 39%;\n"
      "}\n"
      "\n"
      ".width-40 {\n"
      "    width: 40%;\n"
      "}\n"
      "\n"
      ".width-41 {\n"
      "    width: 41%;\n"
      "}\n"
      "\n"
      ".width-42 {\n"
      "    width: 42%;\n"
      "}\n"
      "\n"
      ".width-43 {\n"
      "    width: 43%;\n"
      "}\n"
      "\n"
      ".width-44 {\n"
      "    width: 44%;\n"
      "}\n"
      "\n"
      ".width-45 {\n"
      "    width: 45%;\n"
      "}\n"
      "\n"
      ".width-46 {\n"
      "    width: 46%;\n"
      "}\n"
      "\n"
      ".width-47 {\n"
      "    width: 47%;\n"
      "}\n"
      "\n"
      ".width-48 {\n"
      "    width: 48%;\n"
      "}\n"
      "\n"
      ".width-49 {\n"
      "    width: 49%;\n"
      "}\n"
      "\n"
      ".width-50 {\n"
      "    width: 50%;\n"
      "}\n"
      "\n"
      ".width-51 {\n"
      "    width: 51%;\n"
      "}\n"
      "\n"
      ".width-52 {\n"
      "    width: 52%;\n"
      "}\n"
      "\n"
      ".width-53 {\n"
      "    width: 53%;\n"
      "}\n"
      "\n"
      ".width-54 {\n"
      "    width: 54%;\n"
      "}\n"
      "\n"
      ".width-55 {\n"
      "    width: 55%;\n"
      "}\n"
      "\n"
      ".width-56 {\n"
      "    width: 56%;\n"
      "}\n"
      "\n"
      ".width-57 {\n"
      "    width: 57%;\n"
      "}\n"
      "\n"
      ".width-58 {\n"
      "    width: 58%;\n"
      "}\n"
      "\n"
      ".width-59 {\n"
      "    width: 59%;\n"
      "}\n"
      "\n"
      ".width-60 {\n"
      "    width: 60%;\n"
      "}\n"
      "\n"
      ".width-61 {\n"
      "    width: 61%;\n"
      "}\n"
      "\n"
      ".width-62 {\n"
      "    width: 62%;\n"
      "}\n"
      "\n"
      ".width-63 {\n"
      "    width: 63%;\n"
      "}\n"
      "\n"
      ".width-64 {\n"
      "    width: 64%;\n"
      "}\n"
      "\n"
      ".width-65 {\n"
      "    width: 65%;\n"
      "}\n"
      "\n"
      ".width-66 {\n"
      "    width: 66%;\n"
      "}\n"
      "\n"
      ".width-67 {\n"
      "    width: 67%;\n"
      "}\n"
      "\n"
      ".width-68 {\n"
      "    width: 68%;\n"
      "}\n"
      "\n"
      ".width-69 {\n"
      "    width: 69%;\n"
      "}\n"
      "\n"
      ".width-70 {\n"
      "    width: 70%;\n"
      "}\n"
      "\n"
      ".width-71 {\n"
      "    width: 71%;\n"
      "}\n"
      "\n"
      ".width-72 {\n"
      "    width: 72%;\n"
      "}\n"
      "\n"
      ".width-73 {\n"
      "    width: 73%;\n"
      "}\n"
      "\n"
      ".width-74 {\n"
      "    width: 74%;\n"
      "}\n"
      "\n"
      ".width-75 {\n"
      "    width: 75%;\n"
      "}\n"
      "\n"
      ".width-76 {\n"
      "    width: 76%;\n"
      "}\n"
      "\n"
      ".width-77 {\n"
      "    width: 77%;\n"
      "}\n"
      "\n"
      ".width-78 {\n"
      "    width: 78%;\n"
      "}\n"
      "\n"
      ".width-79 {\n"
      "    width: 79%;\n"
      "}\n"
      "\n"
      ".width-80 {\n"
      "    width: 80%;\n"
      "}\n"
      "\n"
      ".width-81 {\n"
      "    width: 81%;\n"
      "}\n"
      "\n"
      ".width-82 {\n"
      "    width: 82%;\n"
      "}\n"
      "\n"
      ".width-83 {\n"
      "    width: 83%;\n"
      "}\n"
      "\n"
      ".width-84 {\n"
      "    width: 84%;\n"
      "}\n"
      "\n"
      ".width-85 {\n"
      "    width: 85%;\n"
      "}\n"
      "\n"
      ".width-86 {\n"
      "    width: 86%;\n"
      "}\n"
      "\n"
      ".width-87 {\n"
      "    width: 87%;\n"
      "}\n"
      "\n"
      ".width-88 {\n"
      "    width: 88%;\n"
      "}\n"
      "\n"
      ".width-89 {\n"
      "    width: 89%;\n"
      "}\n"
      "\n"
      ".width-90 {\n"
      "    width: 90%;\n"
      "}\n"
      "\n"
      ".width-91 {\n"
      "    width: 91%;\n"
      "}\n"
      "\n"
      ".width-92 {\n"
      "    width: 92%;\n"
      "}\n"
      "\n"
      ".width-93 {\n"
      "    width: 93%;\n"
      "}\n"
      "\n"
      ".width-94 {\n"
      "    width: 94%;\n"
      "}\n"
      "\n"
      ".width-95 {\n"
      "    width: 95%;\n"
      "}\n"
      "\n"
      ".width-96 {\n"
      "    width: 96%;\n"
      "}\n"
      "\n"
      ".width-97 {\n"
      "    width: 97%;\n"
      "}\n"
      "\n"
      ".width-98 {\n"
      "    width: 98%;\n"
      "}\n"
      "\n"
      ".width-99 {\n"
      "    width: 99%;\n"
      "}\n"
      "\n"
      ".width-100 {\n"
      "    width: 100%;\n"
      "}\n";
};

}  // namespace sentinel

#endif  // INCLUDE_SENTINEL_HTMLREPORT_HPP_
